"""add_performance_indexes

Revision ID: bf5cfbb6a13b
Revises: c1f96c3b2c41
Create Date: 2026-02-22 00:51:43.081327

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bf5cfbb6a13b'
down_revision: Union[str, Sequence[str], None] = 'c1f96c3b2c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appt_contact', 'appointments', ['contact_id'], unique=False, if_not_exists=True)
    op.create_index('ix_appt_dept_start', 'appointments', ['department_id', 'scheduled_start'], unique=False, if_not_exists=True)
    op.create_index('ix_appt_reminder', 'appointments', ['status', 'reminder_sent', 'scheduled_start'], unique=False, if_not_exists=True)
    op.create_index('ix_appt_status_start', 'appointments', ['status', 'scheduled_start'], unique=False, if_not_exists=True)
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False, if_not_exists=True)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False, if_not_exists=True)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id', 'created_at'], unique=False, if_not_exists=True)
    op.create_index('ix_calls_contact', 'calls', ['contact_id'], unique=False, if_not_exists=True)
    op.create_index('ix_calls_dept_started', 'calls', ['department_id', 'started_at'], unique=False, if_not_exists=True)
    op.create_index('ix_calls_language', 'calls', ['detected_language'], unique=False, if_not_exists=True)
    op.create_index('ix_calls_resolution', 'calls', ['resolution_status'], unique=False, if_not_exists=True)
    op.create_index('ix_calls_status', 'calls', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_conv_turns_call_seq', 'conversation_turns', ['call_id', 'sequence'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conv_turns_call_seq', table_name='conversation_turns', if_exists=True)
    op.drop_index('ix_calls_status', table_name='calls', if_exists=True)
    op.drop_index('ix_calls_resolution', table_name='calls', if_exists=True)
    op.drop_index('ix_calls_language', table_name='calls', if_exists=True)
    op.drop_index('ix_calls_dept_started', table_name='calls', if_exists=True)
    op.drop_index('ix_calls_contact', table_name='calls', if_exists=True)
    op.drop_index('ix_audit_user', table_name='audit_logs', if_exists=True)
    op.drop_index('ix_audit_resource', table_name='audit_logs', if_exists=True)
    op.drop_index('ix_audit_action_created', table_name='audit_logs', if_exists=True)
    op.drop_index('ix_appt_status_start', table_name='appointments', if_exists=True)
    op.drop_index('ix_appt_reminder', table_name='appointments', if_exists=True)
    op.drop_index('ix_appt_dept_start', table_name='appointments', if_exists=True)
    op.drop_index('ix_appt_contact', table_name='appointments', if_exists=True)
    # ### end Alembic commands ###
